version: '3'
services:
  web:
    command: npm run dev
    ports:
      - '3000:3000'
    volumes:
      - ./config.js:/usr/src/app/config.js
      - ./theme.js:/usr/src/app/theme.js
      - ./images/graphs/:/usr/src/app/public/images/graphs/
      - ./images/footer.png:/usr/src/app/public/images/footer.png
      - ./images/logo.png:/usr/src/app/public/images/logo.png
      - ./images/placeholder.jpg:/usr/src/app/public/images/placeholder.jpg
      - ./images/thumbnail.jpg:/usr/src/app/public/images/thumbnail.jpg
      - ./images/favicon.png:/usr/src/app/public/images/favicon.png
      - ./locales/en/project.json:/usr/src/app/public/static/locales/en/project.json
      - ./locales/en/home.json:/usr/src/app/public/static/locales/en/home.json
      - ./locales/fr/project.json:/usr/src/app/public/static/locales/fr/project.json
      - ./locales/fr/home.json:/usr/src/app/public/static/locales/fr/home.json
      - ./helpers/connectors/limecraft.js:/usr/src/app/src/helpers/connectors/limecraft.js
      - ./pages/api/limecraft/thumbnail.js:/usr/src/app/src/pages/api/limecraft/thumbnail.js
      - ./pages/api/limecraft/video.js:/usr/src/app/src/pages/api/limecraft/video.js
    environment:
      - NODE_ENV=development
